version: '3.0'

services:

    search_gateway:
        image: golang:1.16
        container_name: search-gateway
        working_dir: /app
        restart: always
        volumes:
            - /data/www/site/search_gateway:/app:cached # 重要！！！ 此部分请依据自己的项目位置 进行调整
            - /tmp/search_gateway_job.log:/tmp/job.log:cached
        ports:
            - 12315:8100
        environment:
            TZ: Asia/Shanghai
            NODE_ENV: production
            GO111MODULE: "on"
            GOPROXY: https://goproxy.io
            TERM: xterm
        networks:
            default:
                ipv4_address: 172.38.0.4
        command:  bash -c "cd /app && go mod tidy && make debug_job" # 调试阶段

networks:
    default:
        external:
            name: network_puppeteer_go

